name: Update README

on:
  schedule:
    - cron: '0 1 * * *' # Every day at 01:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install project dependencies
        run: pnpm install --frozen-lockfile
      - name: Build README.md
        run: pnpm start
      - name: Commit
        run: |
          git config --global user.name 'Andrea Simone Costa'
          git config --global user.email 'jfet97@users.noreply.github.com'
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "Updated README"
            git push
          else
            echo "No changes to commit"
          fi
          
